### ISSUE TITLE
Naming, Node version, other thoughts?

### ISSUE THREAD

**Issue by mikefowler** [mikefowler/gatsby-plugin-collections#1]
@KyleAMathews I am using this with good success in a couple of personal projects. Before I put it out into the world, I am curious about:

- whether you have any thoughts on naming ("collections" vs ❓)
- what version of Node I should be targeting with my Babel compilation?
- literally anything else you can think of to reply with

🙌

**Comment by KyleAMathews** [comment]
Ugh, missed responding to this over the break :-(

But here now to rectify that :-)

I think this looks great! Really nice abstraction. "collections" seems like the right name given its wide usage in Jekyll, etc. On Node version — we're still targeting Node 4 so I'd copy that.

But yeah, this is a very useful plugin in its own right and especially help for people coming over from Jekyll.

When I was designing Gatsby's APIs I didn't want to make them too high-level as my hope was we as a community could explore different higher-level APIs together so I'm super excited to see this!

**Comment by mikefowler** [comment]
@KyleAMathews thanks for your thoughts! I'll continue banging this into shape and holler when it's ready for listing on the site!
