### ISSUE TITLE
Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by b3nab** [mikefowler/gatsby-plugin-collections#2]
I receive this error when I don't add the `template: post-template` in markdown file from my collections. And it don't continue creating the pages.

This error is caused by the query in file `src/createPages.js` at line 53, because it seems to be required. If I remove `template` it works like a charm.

I may suggest you to try another way to include templates from markdown, and not from gatbsy-node.js.

**Comment by dhoulb** [comment]
FYI I get a few issues generated by that query:

```
Expected type MarkdownRemarkConnectionSortByFieldsEnum, found fields___date; Did you mean the enum value fields___slug?
Cannot query field "date" on type "fields"
Cannot query field "template" on type "frontmatter"
```

I think the date issues are because none of my *.md files are named in the yyyy-mm-dd format — it's a hierarchical directory of documentation not a list of Blog posts. Is this not designed to work with those?

**Comment by mikefowler** [comment]
@b3nab @dhoulb I've picked this project up again recently, and I'll be releasing a version shortly that should be free of both these issues.

**Comment by mikefowler** [comment]
@b3nab @dhoulb if you're still interested in giving this plugin a go, the most recent version fixes this issue and should be quite stable!

**Comment by dhoulb** [comment]
@mikefowler Appreciate the work but I realised I was looking something slightly different (for the plugin to model the hierarchy of files in a directory for a docs website, rather than a series of blogs) so I ended up [building my own plugin](https://github.com/dhoulb/gatsby-plugin-templated-files). 

I got a bunch of pointers from reading your code though, so thank you!

**Comment by mikefowler** [comment]
🤙 Right on!
